### ISSUE TITLE
Missing instances for Word

### ISSUE THREAD

**Issue by potato4444** [identicalsnowflake/cantor-pairing#3]
Is it intentional that there is no instance for `Word`? there are instances for the fixed width word varieties and Int so it surprises me that the instance is missing.

**Comment by identicalsnowflake** [comment]
Not intentional, just missed that one. There's a few others I should do, too -- I pulled in a dependency on `containers` at the last minute, and I think you're supposed to make instances for any dependencies you incur so others won't have to make orphans. I'll try to make these soon.

**Comment by identicalsnowflake** [comment]
Added word instances in 363daa59acf8d3cc11335b23939e086bd32a0982

**Comment by potato4444** [comment]
I think we can close this once you merge  bugfix #4. We should probably add some tests, might give me a chance to work out how testing tools in haskell work.

**Comment by identicalsnowflake** [comment]
There's tests in the [test folder](https://github.com/identicalsnowflake/cantor-pairing/blob/master/test) -- you can add more if you want. The ones I have are just sanity checks for cardinality and asserting that `(toCantor . fromCantor) = id` for a bunch of different instances.

**Comment by identicalsnowflake** [comment]
You can run them with `cabal test` or `cabal new-test`
